[package]
name = "hv-egui"
version = "0.1.0"
authors = ["Shea Decibel Leffler <shea@errno.com>"]
license = "MIT OR Apache 2.0"
edition = "2018"

[dependencies]
egui = { version = "0.14" }
hv-core = { path = "../hv-core" }
hv-friends = { path = "../hv-friends" }
mlua = "0.6.2"
quad-url = "0.1.1"
