[package]
name = "hv-fmod-sys"
version = "0.1.0"
authors = ["Shea Leffler <shea@errno.com>"]
edition = "2018"
build = "build.rs"

[features]
debug = []

[dependencies]

[build-dependencies]
bindgen = "0.55.1"
