[package]
name = "hv-mymachine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hv-core = { path = "../hv-core" }
anyhow = "1.0.42"
rustyline = "8.2.0"
serde_json = "1.0.66"
mlua = "0.6.2"
